environment:
  nodejs_version: "10"
  CODECOV_TOKEN: "7628da08-1b43-47a1-accb-d38df3827f81"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g codecov

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm test

after_test:
  - codecov
  - ps: ./ci/deploy-docs

build: off