environment:
  nodejs_version: "10"
  CODECOV_TOKEN: "7628da08-1b43-47a1-accb-d38df3827f81"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: ./ci/install
  - npm install -g codecov

build_script:
  - ps: ./ci/build

test_script:
  - node --version
  - npm --version
  - npm test

on_success:
  - codecov
  - ps: ./ci/deploy-docs