environment:
  nodejs_version: "10"
  CODECOV_TOKEN: "12152787-32ad-4227-9eab-4f6af07035f8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g codecov

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm test
  - codecov

build: off