environment:
  nodejs_version: "10"
  CODECOV_TOKEN: "7628da08-1b43-47a1-accb-d38df3827f81"
  GIT_COMMITTER_NAME: t532 via CI
  GIT_COMMITTER_EMAIL: trustq@qq.com

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: "$env:NPM_TOKEN = if ($env:NPM_TOKEN) { $env:NPM_TOKEN } else { \"dummy\" }"
  - npm install
  - npm install -g codecov

build_script:
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

on_success:
  - codecov
  - npm run release
  - ps: ./ci/deploy-docs

skip_tags: true