import { BotWhen } from './classes/when'
/** An object for determining when should a session start */
export const when: BotWhen = new BotWhen().raw().type('message')
export { init } from './app'
export { sender } from './instances/sender'
export { start, receiver } from './instances/receiver'
export { run as runMiddleware, use as useMiddleware } from './instances/middlewares'
export { run as runSession, use as useSession, create as createSessionManager, sessionCount, ISessionContext } from './instances/sessions'
export { TExtensibleMessage } from './instances/definitions'
export * from './classes/sender'
export * from './classes/receiver'
export * from './classes/cqcode'
export * from './classes/when'
export * from './classes/command'
export * from './classes/middleware'
export * from './classes/session'